package db

import "testing"

const (
	nodeCompatMasterKey = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
	// Generated by Node AES-256-GCM using:
	// iv=00112233445566778899aabb
	// plaintext="hello-from-node"
	// format: base64(iv + ciphertext + authTag)
	nodeCompatCiphertextB64 = "ABEiM0RVZneImaq71SNA/WfM2T30no19b8dVzqhK9DcYp1Uq+qa2Qshbjw=="
)

func TestDecrypt_NodeAesGcmBase64Format(t *testing.T) {
	plaintext, err := decrypt(nodeCompatCiphertextB64, nodeCompatMasterKey)
	if err != nil {
		t.Fatalf("decrypt node ciphertext: %v", err)
	}
	if got, want := string(plaintext), "hello-from-node"; got != want {
		t.Fatalf("plaintext mismatch: got %q want %q", got, want)
	}
}

func TestDecrypt_RejectsTooShortCiphertext(t *testing.T) {
	// Base64 for 12-byte IV only (no ciphertext/tag). Must fail.
	tooShort := "ABEiM0RVZneImaq7"
	if _, err := decrypt(tooShort, nodeCompatMasterKey); err == nil {
		t.Fatal("expected decrypt error for too-short ciphertext")
	}
}
